
BASE <http://example.com/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?interaction (COUNT(?response) AS ?numb_resonses)
WHERE {
        ?interaction a <types/interaction>.

        ?response a <types/response>.

        ?interaction <predicates/hasResponseOptions> ?response.

}
GROUP BY ?interaction
ORDER BY DESC(?numb_resonses)